# Use the official PostgreSQL image as a base
FROM postgres:latest

# Environment variables to configure PostgreSQL
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB bl-ti

# Copy the SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/
