version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      APP_CONNECTION_STRING: "Host=db;Port=5432;Database=bl-ti;User Id=postgres;Password=postgres;"
      APP_ENABLE_HTTPS_REDIRECTION: "false"
      APP_JWT_SECRET_KEY: "aVvJIKz0NV14bbdMHL2EORCpIDFkDohA1k9sm3nv"
      APP_JWT_ISSUER: "WebApp.Auth.Dev"
      APP_JWT_AUDIENCE: "WebApp.Dev"
      APP_JWT_EXPIRATION_IN_MINUTES: "10"

  db:
    build:
      context: .
      dockerfile: dockerfile.postgres
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bl-ti
